DELIMITER $$
CREATE PROCEDURE REALIZAR_VENDA (
IN p_cliente_id INT,
IN p_produto_id INT,
IN p_quantidade INT,
)
BEGIN
DECLARE V_ESTOQUE INT;
DECLARE V_VENDA_ID INT;
DECLARE V_PRECO_UNITARIO DECIMAL(10, 2);
START TRANSACTION;
SELECT estoque INTO V_ESTOQUE FROM Produtos WHERE id = p_produto_id;
IF V_ESTOQUE >= p_quantidade THEN
SELECT preco INTO V_PRECO_UNITARIO
INSERT INTO VENDAS SET V_VENDA_ID = LAST_INSERT_ID();
INSERT INTO VENDAS_ITENS(VENDA_ID, PRODUTO_ID, QUANTIDADE, PRECO_UNITARIO)
VALUES (V_VENDA_ID, p_produto_id, p_quantidade, V_PRECO_UNITARIO);
COMMIT;
ELSE
ROLLBACK;
END IF;
END$$

DELIMITER ;
    
